In [1]:
import pandas as pd
import pathlib

from sklearn.naive_bayes import CategoricalNB 
pathlib.Path.cwd()

data=pd.read_csv('data/drug.csv')

     Age Sex      BP Cholesterol        Na         K   Drug
0     23   F    HIGH        HIGH  0.792535  0.031258  drugY
1     47   M     LOW        HIGH  0.739309  0.056468  drugC
2     47   M     LOW        HIGH  0.697269  0.068944  drugC
3     28   F  NORMAL        HIGH  0.563682  0.072289  drugX
4     61   F     LOW        HIGH  0.559294  0.030998  drugY
..   ...  ..     ...         ...       ...       ...    ...
195   56   F     LOW        HIGH  0.848774  0.073380  drugC
196   16   M     LOW        HIGH  0.743021  0.061886  drugC
197   52   M  NORMAL        HIGH  0.549945  0.055581  drugX
198   23   M  NORMAL      NORMAL  0.784520  0.055959  drugX
199   40   F     LOW      NORMAL  0.683503  0.060226  drugX

[200 rows x 7 columns]

In [ ]:
CategoricalNB(alpha=0,)